version: 2
updates:
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
        interval: daily
      labels:
        - "dependabot-github_actions"
        - "dependencies"
      groups:
        github-actions-dependencies:
            patterns:
                - "*"
