name: Build Websites

on:
    workflow_run:
        workflows:
            - Check Build Script
        branches:
            - main
        type:
            - completed
    workflow_dispatch:

jobs:
    build-website-and-send-to-server:
        runs-on: ubuntu-latest
        permissions:
            contents: read

        if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push'

        steps:
            - name: Install Python Project
              uses: CarrotManMatt/action-install-python-project@v2
              with:
                  python-version: 3.12
                  directory: "./.build"

            - name: Run Build Script
              run: poetry -C "./.build" run python ./.build/main.py  # Save output to variable

            - name: Send To Webserver
              run: "false"  # Send output from previous job's output
