name: Check, Build and Deploy All Websites

on:
    pull_request:
        branches: [main]
    push:
        branches: [main]
    schedule:
        - cron: 48 5 * * 1
    workflow_dispatch:

jobs:
    uv-check:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Install uv
              uses: astral-sh/setup-uv@v5
              with:
                enable-cache: true

            - name: Check uv.lock (ensure all dependencies up to date)
              run: uv lock --check --project .build_and_deploy

    djlint:
        runs-on: ubuntu-latest
        env:
            UV_NO_SYNC: true
            UV_FROZEN: true
            UV_PYTHON_DOWNLOADS: never

        steps:
            - uses: actions/checkout@v4

            - name: Set Up Python
              uses: actions/setup-python@v5
              with:
                python-version-file: .build_and_deploy/.python-version

            - name: Install uv
              uses: astral-sh/setup-uv@v5
              with:
                enable-cache: true

            - name: Install djLint From Locked Dependencies
              run: uv sync --project .build_and_deploy --only-group lint-format

            - name: Run djLint
              run: uv run --project .build_and_deploy -- djlint . --configuration .build_and_deploy/pyproject.toml

    mypy:
        needs: [uv-check]
        runs-on: ubuntu-latest
        env:
            UV_NO_SYNC: true
            UV_FROZEN: true
            UV_PYTHON_DOWNLOADS: never

        steps:
            - uses: actions/checkout@v4

            - name: Set Up Python
              uses: actions/setup-python@v5
              with:
                python-version-file: .build_and_deploy/.python-version

            - name: Install uv
              uses: astral-sh/setup-uv@v5
              with:
                enable-cache: true

            - name: Install mypy From Locked Dependencies
              run: uv sync --project .build_and_deploy --no-group dev --group type-check

            - name: Store Hashed Python Version
              id: store-hashed-python-version
              run: echo "hashed_python_version=$(uv run -- python -VV | sha256sum | cut -d' ' -f1)"
                >> $GITHUB_OUTPUT

            - uses: actions/cache@v4
              with:
                path: ./.mypy_cache
                key: mypy|${{steps.store-hashed-python-version.outputs.hashed_python_version}}

            - name: Run mypy
              run: uv run --project .build_and_deploy -- mypy .build_and_deploy  # TODO: Add GitHub workflows output format

    pre-commit:
        runs-on: ubuntu-latest
        env:
            UV_NO_SYNC: true
            UV_FROZEN: true
            UV_PYTHON_DOWNLOADS: never

        steps:
            - uses: actions/checkout@v4

            - name: Set Up Python
              uses: actions/setup-python@v5
              with:
                python-version-file: .build_and_deploy/.python-version

            - name: Install uv
              uses: astral-sh/setup-uv@v5
              with:
                enable-cache: true

            - name: Install pre-commit From Locked Dependencies
              run: uv sync --project .build_and_deploy --only-group pre-commit

            - name: Store Hashed Python Version
              id: store-hashed-python-version
              run: echo "hashed_python_version=$(uv run --project .build_and_deploy -- python -VV
                | sha256sum | cut -d' ' -f1)" >> $GITHUB_OUTPUT

            - uses: actions/cache@v4
              with:
                path: ~/.cache/pre-commit
                key: pre-commit|${{steps.store-hashed-python-version.outputs.hashed_python_version}}|${{hashFiles('.pre-commit-config.yaml')}}

            - name: Setup pre-commit Environments
              run: uv run --project .build_and_deploy -- pre-commit install-hooks

            - name: Save pre-commit Checks Which Require Skipping
              run: echo "SKIP=check-github-workflows,djlint-django,ruff,uv-lock" >> $GITHUB_ENV

            - name: Run pre-commit
              run: uv run --project .build_and_deploy -- pre-commit run --all-files --hook-stage
                manual  # TODO: Add GitHub workflows output format

    ruff-lint:
        runs-on: ubuntu-latest
        env:
            UV_NO_SYNC: true
            UV_FROZEN: true
            UV_PYTHON_DOWNLOADS: never

        steps:
            - uses: actions/checkout@v4

            - name: Set Up Python
              uses: actions/setup-python@v5
              with:
                python-version-file: .build_and_deploy/.python-version

            - name: Install uv
              uses: astral-sh/setup-uv@v5
              with:
                enable-cache: true

            - name: Install ruff From Locked Dependencies
              run: uv sync --project .build_and_deploy --only-group lint-format

            - name: Store Hashed Python Version
              id: store-hashed-python-version
              run: echo "hashed_python_version=$(uv run --project .build_and_deploy -- python -VV
                | sha256sum | cut -d' ' -f1)" >> $GITHUB_OUTPUT

            - uses: actions/cache@v4
              with:
                path: ./.ruff_cache
                key: ruff|${{steps.store-hashed-python-version.outputs.hashed_python_version}}

            - name: Run Ruff
              run: uv run --project .build_and_deploy -- ruff check --no-fix --output-format=github

    build-and-deploy:
        name: Build and Deploy All Websites
        runs-on: ubuntu-latest
        environment: deploy
        needs: [djlint, mypy, pre-commit, ruff-lint, uv-check]
        permissions:
            contents: read

        if: github.event_name == 'push' || github.event_name == 'schedule' || github.event_name ==
            'workflow_dispatch'

        steps:
            - uses: actions/checkout@v4

            - name: Set Up Python
              uses: actions/setup-python@v5
              with:
                python-version-file: .build_and_deploy/.python-version

            - name: Install uv
              uses: astral-sh/setup-uv@v5
              with:
                enable-cache: true

            - name: Install Project
              run: uv sync --project .build_and_deploy --no-group dev

            - uses: twingate/github-action@v1
              with:
                service-key: ${{secrets.TWINGATE_SERVICE_KEY}}

            - uses: webfactory/ssh-agent@v0.9.0
              with:
                ssh-private-key: ${{secrets.SSH_PRIVATE_KEY}}

            - name: Run Build & Deploy Script
              env:
                STATIC_WEBSITES_BUILDER_REMOTE_DIRECTORY: ${{secrets.REMOTE_DIRECTORY}}
                STATIC_WEBSITES_BUILDER_REMOTE_IP: ${{secrets.REMOTE_IP}}
                STATIC_WEBSITES_BUILDER_REMOTE_USERNAME: ${{secrets.REMOTE_USERNAME}}

              run: uv run --directory .build_and_deploy -m console
