name: Check, Build and Deploy All Websites

on:
    pull_request:
        branches:
            - "main"
    push:
        branches:
            - "main"

    schedule:
        - cron: "47 5 * * 1"

    workflow_dispatch:

jobs:
    mypy:
        runs-on: ubuntu-latest

        steps:
            - name: Install Python Project
              uses: CarrotManMatt/action-install-python-project@v2
              with:
                  python-version: 3.12
                  directory: "./.build_and_deploy"

            - name: Run mypy
              working-directory: ./.build_and_deploy
              run: poetry run mypy .

    ruff:
        runs-on: ubuntu-latest

        steps:
            - name: Install Python Project
              uses: CarrotManMatt/action-install-python-project@v2
              with:
                  python-version: 3.12
                  directory: "./.build_and_deploy"

            - name: Run Ruff
              working-directory: ./.build_and_deploy
              run: poetry run ruff check --no-fix

    djlint:
        runs-on: ubuntu-latest

        steps:
            - name: Install Python Project
              uses: CarrotManMatt/action-install-python-project@v2
              with:
                  python-version: 3.12
                  directory: "./.build_and_deploy"

            - name: Run djLint
              working-directory: ./.build_and_deploy
              run: poetry run djlint .. --lint --configuration pyproject.toml

    build-and-deploy-websites:
        name: Build and Deploy All Websites
        runs-on: ubuntu-latest
        permissions:
            contents: read

        needs: [mypy, ruff, djlint]

        if: github.event == 'push'

        steps:
            - name: Install Python Project
              uses: CarrotManMatt/action-install-python-project@v2
              with:
                  python-version: 3.12
                  directory: "./.build_and_deploy"

            - name: Run Build Script
              working-directory: ./.build_and_deploy
              run: poetry run python -m console  # TODO: add arguments
