name: Check, Build and Deploy All Websites

on:
    pull_request:
        branches:
            - "main"
    push:
        branches:
            - "main"

    workflow_dispatch:

jobs:
    mypy:
        runs-on: ubuntu-latest

        steps:
            - name: Install Python Project
              uses: CarrotManMatt/action-install-python-project@v2
              with:
                  python-version: 3.12
                  directory: "./.build_and_deploy"

            - name: Run mypy
              run: poetry -C "./.build_and_deploy" run mypy .build_and_deploy

    ruff:
        runs-on: ubuntu-latest

        steps:
            - name: Install Python Project
              uses: CarrotManMatt/action-install-python-project@v2
              with:
                  python-version: 3.12
                  directory: "./.build_and_deploy"

            - name: Run Ruff
              run: poetry -C "./.build_and_deploy" run ruff check .build_and_deploy --no-fix

    djlint:
        runs-on: ubuntu-latest

        steps:
            - name: Install Python Project
              uses: CarrotManMatt/action-install-python-project@v2
              with:
                  python-version: 3.12
                  directory: "./.build_and_deploy"

            - name: Run djLint
              run: poetry -C "./.build_and_deploy" run djlint . --lint

    build-and-deploy-websites:
        name: Build and Deploy All Websites
        runs-on: ubuntu-latest
        permissions:
            contents: read

        needs: [mypy, ruff, djlint]

        if: github.event == 'push'

        steps:
            - name: Install Python Project
              uses: CarrotManMatt/action-install-python-project@v2
              with:
                  python-version: 3.12
                  directory: "./.build_and_deploy"

            - name: Run Build Script
              run: poetry -C "./.build_and_deploy" run python ./.build_and_deploy/__main__.py  # TODO: add arguments
