name: Check, Build and Deploy All Websites

on:
    pull_request:
        branches:
            - "main"
    push:
        branches:
            - "main"

    schedule:
        - cron: "47 5 * * 1"

    workflow_dispatch:

jobs:
    yamllint:
        runs-on: ubuntu-latest

        steps:
            - name: Install Python Project
              uses: CarrotManMatt/action-install-python-project@v2
              with:
                  python-version: 3.12
                  directory: "./.build_and_deploy"

            - name: Test CWD
              working-directory: .build_and_deploy
              run: poetry run python -m yamllint

            - name: Run yamllint
              working-directory: .build_and_deploy
              run: poetry run python -m yamllint . -s -f colored

    mypy:
        runs-on: ubuntu-latest

        steps:
            - name: Install Python Project
              uses: CarrotManMatt/action-install-python-project@v2
              with:
                  python-version: 3.12
                  directory: "./.build_and_deploy"

            - name: Test CWD
              working-directory: .build_and_deploy
              run: poetry run python -m mypy

            - name: Run mypy
              working-directory: .build_and_deploy
              run: poetry run python -m mypy .

    ruff:
        runs-on: ubuntu-latest

        steps:
            - name: Install Python Project
              uses: CarrotManMatt/action-install-python-project@v2
              with:
                  python-version: 3.12
                  directory: "./.build_and_deploy"

            - name: Test CWD
              working-directory: .build_and_deploy
              run: poetry run python -m ruff

            - name: Run Ruff
              working-directory: .build_and_deploy
              run: poetry run python -m ruff check --no-fix

    djlint:
        runs-on: ubuntu-latest

        steps:
            - name: Install Python Project
              uses: CarrotManMatt/action-install-python-project@v2
              with:
                  python-version: 3.12
                  directory: "./.build_and_deploy"

            - name: Test CWD
              working-directory: .build_and_deploy
              run: poetry run python -m djlint

            - name: Run djLint
              working-directory: .build_and_deploy  # TODO: fix commands not available in working directory
              run: poetry run python -m djlint .. --lint --configuration pyproject.toml

    build-and-deploy-websites:
        name: Build and Deploy All Websites
        runs-on: ubuntu-latest
        permissions:
            contents: read

        environment: "deploy"

        needs: [mypy, ruff, yamllint, djlint]

        if: github.event == 'push'

        steps:
            - name: Install Python Project
              uses: CarrotManMatt/action-install-python-project@v2
              with:
                  python-version: 3.12
                  directory: "./.build_and_deploy"

            # TODO: Add step to login with Twingate (https://www.twingate.com/docs/example-cicd-configurations)

            - uses: webfactory/ssh-agent@v0.9.0
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Run Build Script
              working-directory: ./.build_and_deploy
              env:
                  REMOTE_IP: ${{ secrets.REMOTE_IP }}
                  REMOTE_USERNAME: ${{ secrets.REMOTE_USERNAME }}
                  REMOTE_DIRECTORY: ${{ secrets.REMOTE_DIRECTORY }}
              run: poetry run python -m console --remote-username "$REMOTE_USERNAME" --remote-directory "$REMOTE_DIRECTORY" "$REMOTE_IP"
