---
name: Check, Build and Deploy All Websites

on:  # yamllint disable-line rule:truthy
    pull_request:
        branches:
            - main
    push:
        branches:
            - main

    schedule:
        - cron: 47 5 * * 1

    workflow_dispatch:  # yamllint disable-line rule:empty-values

jobs:  # yamllint disable-line rule:key-ordering
    djlint:
        runs-on: ubuntu-latest

        steps:
            - name: Install Python Project
              uses: CarrotManMatt/action-install-python-project@v2
              with:
                  directory: ./.build_and_deploy
                  python-version: 3.12

            - name: Run djLint
              working-directory: .build_and_deploy
              run: poetry run python -m djlint .. --lint --configuration pyproject.toml  # yamllint disable-line rule:key-ordering rule:line-length

    mypy:
        runs-on: ubuntu-latest

        steps:
            - name: Install Python Project
              uses: CarrotManMatt/action-install-python-project@v2
              with:
                  directory: ./.build_and_deploy
                  python-version: 3.12

            - name: Run mypy
              working-directory: .build_and_deploy
              run: poetry run python -m mypy .  # yamllint disable-line rule:key-ordering

    ruff:
        runs-on: ubuntu-latest

        steps:
            - name: Install Python Project
              uses: CarrotManMatt/action-install-python-project@v2
              with:
                  directory: ./.build_and_deploy
                  python-version: 3.12

            - name: Run Ruff
              working-directory: .build_and_deploy
              run: poetry run python -m ruff check --no-fix  # yamllint disable-line rule:key-ordering rule:line-length

    yamllint:
        runs-on: ubuntu-latest

        steps:
            - name: Install Python Project
              uses: CarrotManMatt/action-install-python-project@v2
              with:
                  directory: ./.build_and_deploy
                  python-version: 3.12

            - name: Run yamllint
              working-directory: .build_and_deploy
              run: poetry run python -m yamllint .. -s -f colored  # yamllint disable-line rule:key-ordering rule:line-length

    build-and-deploy-websites:  # yamllint disable-line rule:key-ordering
        name: Build and Deploy All Websites
        needs: [djlint, mypy, ruff, yamllint]
        # yamllint disable-line rule:key-ordering
        if: >-
            github.event_name == 'push'
            || github.event_name == 'schedule'
            || github.event_name == 'workflow_dispatch'
        permissions:
            contents: read
        runs-on: ubuntu-latest

        steps:
            - name: Test event type
              run: echo ${{ github.event_name }}
