name: Check And Build Websites

on:
    pull_request:
        branches:
            - "main"
    push:
        branches:
            - "main"

    workflow_dispatch:

jobs:
    mypy:
        runs-on: ubuntu-latest

        steps:
            - name: Install Python Project
              uses: CarrotManMatt/action-install-python-project@v2
              with:
                  python-version: 3.12
                  directory: "./.build"

            - name: Run mypy
              run: poetry -C "./.build" run mypy .build

    ruff:
        runs-on: ubuntu-latest

        steps:
            - name: Install Python Project
              uses: CarrotManMatt/action-install-python-project@v2
              with:
                  python-version: 3.12
                  directory: "./.build"

            - name: Run Ruff
              run: poetry -C "./.build" run ruff check .build --no-fix

    djlint:
        runs-on: ubuntu-latest
        needs: [mypy, ruff]

        steps:
            - name: Install Python Project
              uses: CarrotManMatt/action-install-python-project@v2
              with:
                  python-version: 3.12
                  directory: "./.build"

            - name: Run djLint
              run: poetry -C "./.build" run djlint . --lint

    build-website-and-send-to-server:
        runs-on: ubuntu-latest
        permissions:
            contents: read

        needs: [djlint]

        if: github.event == 'push'

        steps:
            - name: Install Python Project
              uses: CarrotManMatt/action-install-python-project@v2
              with:
                  python-version: 3.12
                  directory: "./.build"

            - name: Run Build Script
              run: poetry -C "./.build" run python ./.build/main.py  # Save output to variable

            - name: Send To Webserver
              run: "false"  # Send output from previous job's output
