---
name: Check, Build and Deploy All Websites

on:  # yamllint disable-line rule:truthy
    pull_request:
        branches:
            - main
    push:
        branches:
            - main

    schedule:
        - cron: 47 5 * * 1

    workflow_dispatch:  # yamllint disable-line rule:empty-values

jobs:  # yamllint disable-line rule:key-ordering
    djlint:
        runs-on: ubuntu-latest

        steps:
            - name: Install Python Project
              uses: CarrotManMatt/action-install-python-project@v2
              with:
                  directory: ./.build_and_deploy
                  python-version: 3.12

            - name: Run djLint
              working-directory: .build_and_deploy
              run: poetry run python -m djlint .. --lint --configuration pyproject.toml  # yamllint disable-line rule:key-ordering rule:line-length

    mypy:
        runs-on: ubuntu-latest

        steps:
            - name: Install Python Project
              uses: CarrotManMatt/action-install-python-project@v2
              with:
                  directory: ./.build_and_deploy
                  python-version: 3.12

            - name: Run mypy
              working-directory: .build_and_deploy
              run: poetry run python -m mypy .  # yamllint disable-line rule:key-ordering

    ruff:
        runs-on: ubuntu-latest

        steps:
            - name: Install Python Project
              uses: CarrotManMatt/action-install-python-project@v2
              with:
                  directory: ./.build_and_deploy
                  python-version: 3.12

            - name: Run Ruff
              working-directory: .build_and_deploy
              run: poetry run python -m ruff check --no-fix  # yamllint disable-line rule:key-ordering rule:line-length

    yamllint:
        runs-on: ubuntu-latest

        steps:
            - name: Install Python Project
              uses: CarrotManMatt/action-install-python-project@v2
              with:
                  directory: ./.build_and_deploy
                  python-version: 3.12

            - name: Run yamllint
              working-directory: .build_and_deploy
              run: poetry run python -m yamllint .. -s -f colored  # yamllint disable-line rule:key-ordering rule:line-length

    build-and-deploy-websites:  # yamllint disable-line rule:key-ordering
        name: Build and Deploy All Websites
        environment: deploy  # yamllint disable-line rule:key-ordering
        if: github.event == 'push' || github.event == 'schedule' || github.event == 'workflow_dispatch'        # yamllint disable-line rule:key-ordering rule:line-length
        needs: [djlint, mypy, ruff, yamllint]
        permissions:
            contents: read
        runs-on: ubuntu-latest

        steps:
            - name: Test event type
              run: echo ${{ github.event }}

#            - name: Install Python Project
#              uses: CarrotManMatt/action-install-python-project@v2
#              with:
#                  directory: ./.build_and_deploy
#                  python-version: 3.12
#
#            - uses: twingate/github-action@v1
#              with:
#                  service-key: ${{ secrets.TWINGATE_SERVICE_KEY }}  # TODO: create service key
#
#            -  # noinspection SpellCheckingInspection
#                uses: webfactory/ssh-agent@v0.9.0
#                with:
#                    ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
#
#            - name: Run Build Script
#              env:  # yamllint disable-line rule:key-ordering
#                  REMOTE_DIRECTORY: ${{ secrets.REMOTE_DIRECTORY }}
#                  REMOTE_IP: ${{ secrets.REMOTE_IP }}
#                  REMOTE_USERNAME: ${{ secrets.REMOTE_USERNAME }}
#              working-directory: ./.build_and_deploy
#              # yamllint disable-line rule:key-ordering
#              run: >-
#                  poetry run
#                  python -m
#                  console
#                  --remote-directory "$REMOTE_DIRECTORY"
#                  --remote-username "$REMOTE_USERNAME"
#                  "$REMOTE_IP"
