name: Check Build Script

on:
    pull_request:
        branches: [ "main" ]
    push:
        branches: [ "main" ]

jobs:
    mypy:
        runs-on: ubuntu-latest

        steps:
            - name: Install Python Project
              uses: CarrotManMatt/action-install-python-project@v2
              with:
                  python-version: 3.12
                  directory: "./.build"

            - name: Run mypy
              run: poetry -C "./.build" run mypy .build

    ruff:
        runs-on: ubuntu-latest

        steps:
            - name: Install Python Project
              uses: CarrotManMatt/action-install-python-project@v2
              with:
                  python-version: 3.12
                  directory: "./.build"

            - name: Run Ruff
              run: poetry -C "./.build" run ruff check .build --no-fix
